name: Auto-Restart Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Force restart every 6 hours
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - name: Run Bot with Auto-Restart
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          while true; do
            python bot.py || echo "Bot crashed, restarting..."
            sleep 10
          done
